name: Keep Vercel Warm

on:
  schedule:
    - cron: "*/1 * * * *" # mỗi 5 phút
  workflow_dispatch: # cho phép chạy thủ công
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Gửi request đến các route chính
        run: |
          urls=(
            "https://mobile-shop-smoky.vercel.app"
            
          )
          for url in "${urls[@]}"; do
            echo "🔁 Pinging $url..."
            curl --silent --show-error --fail "$url" && echo "✅ $url OK" || echo "❌ $url Failed"
          done
